import './globals.css'
import { Poppins } from 'next/font/google'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const inter = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ title, children }) {
  return (
    <html lang="en">
      <body className={`Poppin flex flex-col justify-between min-h-screen`}>
        <Header />
        <main className="">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
